### ISSUE TITLE
r.uri does not contain request arguments

### ISSUE THREAD

**Issue by clijsters** [tippexs/nginx-njs-waf-cve2021-44228#1]
Thanks for that mitigation scripts, which I like!

However, when called with `GET http://localhost/test?${vulnerable}`, `${r.uri}` evaluates to `/test` in [cve.js#L15](https://github.com/tippexs/nginx-njs-waf-cve2021-44228/blob/main/cve.js#L15).

When replaced with `${r.rawVariables.request_uri}`, the malicious parameters are taken into account, which I'd prefer.

Best Regards

**Comment by tippexs** [comment]
That is totally right! Sorry missed that! Thanks for submitting this.
