### ISSUE TITLE
invalid URL prefix in "undefined" when send non-POST request to location

### ISSUE THREAD

**Issue by fogmorn** [tippexs/nginx-njs-waf-cve2021-44228#6]
Hello and thank you for the script!

I have found that when non-POST request comes to a location which is configured to scan POST-Body data, I got following error:

```
curl --location --request GET 'http://test2.lan/your-location/'

/var/log/nginx/error.log:
2021/12/18 08:06:08 [error] 18966#18966: *52 invalid URL prefix in "undefined", client: 172.16.99.158, server: ipa2.lan, request: "GET /your-location/ HTTP/1.1", host: "ipa2.lan"
```

The location configuration is: 
```
location /your-location/ {
   set $upstream "http://127.0.0.1:8099";
   mirror /_scannBodyJNDI;
   proxy_pass $bodyScanned;
}
```

I suppose this can be fixed by adding conditional to `postBodyInspect` function in `cvs.js`:
```javascript
else if (r.method === 'GET') {return r.variables.upstream};
```
or 
```javascript
else {return r.variables.upstream};
```

Or it must be fixed on virtual host configuration level?

What do you think?

**Comment by tippexs** [comment]
Hi - thanks for finding this little bug. It is fixed now.
